#' Assess Completeness - Crude Missing
#'
#' @param data - arrow data table
#' @param metadata - item level metadata, expected data table object generated by prep_metadata function
#' @param cross_item_metadata - cross level metadata,  expected data table object generated by prep_metadata function
#'
#' @return 2 data.frame for univariate and multivariate missingness result
#' 
#' @import data.table arrow tidyverse 
#' @export
#'
#' @examples
com_crude_missing <- function(data, item_metadata, cross_item_metadata){
  # list all variables in data 
  # load multivariate variable list and contradictions
  multivariate_vars <- cross_item_metadata[["multivariate_vars"]]

  # extract relevant columns
  multivariate_vars <- as.data.frame(multivariate_vars[check_missing==TRUE,c("variables")])
  
  # get total number of data
  no_data <- data$num_rows
  
  # --- Check missingness for each variable
  varname <- character(0)
  no_missing <- character(0)
  percentage <- double()
  
  for(var in data$ColumnNames()){
    curr_varname <- var
    # curr_no_missing <- data$Filter(is.na(data[[var]]))$num_rows
    curr_no_missing <- data[[var]]$null_count
    # print(str_interp("${curr_varname} has ${curr_no_missing} NA values out of ${no_data}"))
    
    # append results to the list of varnames and missing values 
    varname <- append(varname, curr_varname)
    no_missing <- append(no_missing, (str_interp("${curr_no_missing}/${no_data}")))
    percentage <- append(percentage, curr_no_missing/no_data)
    
    gc()
  }
  univariate_result <- data.frame(varname, no_missing, percentage)
  print(univariate_result)
  
  # --- Check missingness for each multivariate 
  varnames <- character(0)
  no_missing <- character(0)
  percentage <- double()
  
  for(row in 1:nrow(multivariate_vars)){
    curr_varnames <- multivariate_vars[row, "variables"]
    # split to get list of varnames
    curr_varnames <- str_replace_all(curr_varnames, " \\| ", " ")
    
    splitted_varnames <- str_split(curr_varnames, " ")[[1]]
    curr_no_missing <- data
    for(var in splitted_varnames){
      curr_no_missing <- curr_no_missing$Filter(is.na(curr_no_missing[[var]]))
  
    }
    curr_no_missing <- curr_no_missing$num_rows

    # deallocate memory before next iteration
    gc()
    
    varnames <- append(varnames, curr_varnames)
    no_missing <- append(no_missing, (str_interp("${curr_no_missing}/${no_data}")))
    percentage <- append(percentage, curr_no_missing/no_data)
  }
  multivariate_result <- data.frame(varnames, no_missing, percentage)
  
  result <- list("univariate_result"=univariate_result, "multivariate_result"=multivariate_result)
  return(result)
}

