#' Assess Consistency - Range of values
#'
#' @param data - arrow data table
#' @param metadata - item level metadata, expected data table object generated by prep_metadata function
#'
#' @return result summary data.frame
#' @import data.table arrow tidyverse 
#' @importFrom stats setNames 
#' @export
#'
#' @examples
con_range <- function(data, metadata, plot_result = FALSE){
  # whether values of column within specified range in metadata
  var_range <- metadata[!is.na(limit), c("variable", "datatype", "limit")]
  
  if(nrow(var_range)==0){
    # if no range is defined, just return immediately
    return(NULL)
  }
  
  # cast type for casting range before comparing 
  cast_type <- setNames(
    list(
      arrow::int32(), arrow::float32(), arrow::date32()
    ),
    nm = c(
      "integer", "float", "datetime"
    )
  ) 
  
  # extract range signs
  inclusive_signs <- as.data.frame(str_extract_all(var_range$limit, "[\\[\\]()]", simplify=TRUE))
  colnames(inclusive_signs) <- c("greater", "less")
  
  # extract values and cast to the specified values
  extracted_limit <- str_remove_all(var_range$limit, "[\\[\\]()]")
  splitted_range <- as.data.frame(str_split(extracted_limit, ",", simplify=TRUE))
  colnames(splitted_range) <- c("lower_bound", "higher_bound")
  
  var_range <- as.data.frame(cbind(var_range, inclusive_signs, splitted_range))
  
  if(ncol(splitted_range) != 2){
    stop("Value does not match expected format
        Expected format: [a, b] or (a, b) or [a, b) or (a, b] where a, b is numeric or date")
  }
  
  # --- Initialize return lists
  varname <- character(0)
  range <- character(0)
  no_inconsistent_range <- character(0)
  percentage_inconsistent <- double()
  no_data <- nrow(data)
  
  for (row in 1:nrow(var_range)){
    curr_varname <- var_range[row, "variable"]
    data <- data %>%
      mapping_filter_condition(.data[[curr_varname]],
                               datatype = var_range[row, "datatype"],
                               lower_bound=var_range[row, "lower_bound"],
                               higher_bound = var_range[row, "higher_bound"],
                               greater = var_range[row, "greater"],
                               less = var_range[row, "less"]
      )
    no_inconsistent <- no_data - nrow(data)
    
    varname <- append(varname, curr_varname)
    range <- append(range, var_range[row, "limit"])
    no_inconsistent_range <- append(no_inconsistent_range, str_interp("${no_inconsistent}/${no_data}"))
    percentage_inconsistent <- append(percentage_inconsistent, no_inconsistent*100/no_data)
  }
  
  result <- data.frame(varname,range, no_inconsistent_range, percentage_inconsistent)
  
  if (plot_result){
    print(util_graphing_percentage(result, varname, percentage = percentage_inconsistent,
                                   title = "Percentage of data with out-of-range values"))
  }
  return()
}