#' Assess Consistency - Valid labels for categorical labels
#'
#' @param data - arrow data table
#' @param metadata - item level metadata, expected data table object generated by prep_metadata function
#' @param path - path to item level metadata 
#'
#' @return result summary for consistency assessment 
#' 
#' @import data.table reticulate arrow tidyverse 
#' @importFrom sets as.set
#' @export
#'
#' @examples
#' 
con_label <- function(data, metadata, path=NULL){
  path <- file.path(path, "item_level.xlsx")
  
  # get variables with defined labels
  var_label <- as.data.frame(metadata[!is.na(labels), c("variable", "datatype", "labels")])
  no_data <- data$num_rows
  
  varname <- character(0)
  no_inconsistent_label <- character(0)
  percentage_inconsistent <- double()
  invalid_labels <- character(0)
  missing_labels <- character(0)

  for (row in 1:nrow(var_label)){
    curr_varname <- var_label[row, "variable"]
    labels <- var_label[row, "labels"]

    # check whether defined labels is a list or point to another sheet
    if(str_detect(labels, "\\|")){
      labels <- Array$create(str_split(labels, " \\| ")[[1]])
    }else{
      if (is.null(path)){
        stop("Path to metadata folder is not given")
      }
      labels <- read_excel(path, sheet = labels)
      
      if(is.null(labels$labels) || length(labels$labels)==0){
        stop(str_interp("Valid labels for ${curr_varname} not defined"))
      }
      
      # convert labels to a list type for consistency
      
      labels <- Array$create(labels$labels)
    }
    
    
    # load data in-memory before standardizing and checking
    values_list <- data[[curr_varname]]$as_vector()
    values_list <- tolower(str_replace_all(values_list, "[:punct:]", " "))

    labels_list <- labels$as_vector()
    labels_list <- tolower(str_replace_all(labels_list, "[:punct:]", " "))
    
    labels_set <- as.set(labels_list)
    no_invalid_label <- no_data - length(which((values_list %in% labels_set)))
    
    values_set <- as.set(values_list)
    
    varname <- append(varname, curr_varname)
    no_inconsistent_label <- append(no_inconsistent_label, str_interp("${no_invalid_label}/${no_data}"))
    percentage_inconsistent <- append(percentage_inconsistent, no_invalid_label/no_data)
    invalid_labels <- append(invalid_labels, paste(values_set - labels_set, collapse=", "))
    missing_labels <- append(missing_labels, paste(labels_set - values_set, collapse=", "))
    
    # deallocate memory for next iteration
    rm(labels_list)
    rm(values_list)
    rm(labels_set)
    rm(values_set)
    gc()
  } 
  
  gc()
  return(data.frame(varname, no_inconsistent_label, percentage_inconsistent, invalid_labels, missing_labels))
}