#' Assess Consistency - Value Contradiction
#' Summarize how much data has contradicting values, and return the rows with contradicting values
#'
#' @param data - arrow data table
#' @param metadata - item level metadata, expected data table object generated by prep_metadata function
#'
#' @return list containing 2 items:
#' - result summary (data.frame)
#' - contradicted data (tibble)
#' @import rlang data.table lubridate tidyverse arrow 
#' @export
#'
#' @examples
con_contradiction <- function(data, metadata, plot_result = FALSE){
  # load multivariate variable list and contradictions
  multivariate_vars <- metadata[["multivariate_vars"]]
  contradiction <-  metadata[["contradictions"]]
  
  # perform table joining to extract variables that needed to check contradiction
  joined <- multivariate_vars[contradiction, on = .(label)]
  # extract relevant columns
  joined <- as.data.frame(joined[,c("variables", "label", "contradiction", "rule")])

  # get the total number of data
  no_data <- data$num_rows
  
  # instantiate columns for return dataframe
  varname <- character(0)
  rule <- character(0)
  no_contradict <- character(0)
  percentage <- double()
  
  # list of contradicted data for each rules
  contradicted_dataset <- list()
  
  for (row in 1:nrow(joined)){
    variables <- joined[row, "variables"]
    
    variables_comb <- str_split(variables, " \\| ")[[1]]
    
    if (length(variables_comb) < 2){
      stop("need at least 2 variables for comparison")
    }
    
    expression <- joined[row, "contradiction"]
    
    # special handling for dates in expression
    dates <- str_extract_all(joined[row, "contradiction"], "\\d{2}/\\d{2}/\\d{4}")[[1]]
    for (date_val in dates){
      expression <- str_replace_all(expression, date_val, str_interp("dmy(\"${date_val}\")"))
    }
    # print(expression)
    
    
    # --- Get contradicted data
    contradicted_data <- data
    
    # only treat expression as a single one
    # must follow R convention
    exp <- str_interp("contradicted_data <- contradicted_data %>% dplyr::filter(${expression})")
    eval(parse_expr(exp))
    
    # --- Update result table
    varname <- append(varname, variables)
    rule <- append(rule, joined[row, "rule"])
    no_contradict <- append(no_contradict, str_interp("${nrow(contradicted_data)}/${no_data}"))
    percentage <- append(percentage, (nrow(contradicted_data)*100/no_data))
    
    # --- Update contradicted data for current rule 
    contradicted_dataset[[joined[row, "label"]]] <- contradicted_data
  }
  
  gc()
  result <- data.frame(varname, rule, no_contradict, percentage)
  
  if (plot_result){
    print(util_graphing_percentage(result, rule, title = "Percentage of contradicted data"))
  }
  
  return(list("contradicted_data" = contradicted_dataset, "result" = result))
}