#' Assess Consistency - Value Contradiction
#' Summarize how much data has contradicting values, and return the rows with contradicting values
#'
#' @param data - arrow data table
#' @param metadata - item level metadata, expected data table object generated by prep_metadata function
#'
#' @return list containing 2 items:
#' - result summary (data.frame)
#' - contradicted data (tibble)
#' @import rlang data.table lubridate tidyverse arrow 
#' @export
#'
#' @examples
con_contradiction <- function(data, metadata){
  # load multivariate variable list and contradictions
  multivariate_vars <- metadata[["multivariate_vars"]]
  contradiction <-  metadata[["contradictions"]]
  
  # perform table joining to extract variables that needed to check contradiction
  joined <- multivariate_vars[contradiction, on = .(label)]
  # extract relevant columns
  joined <- as.data.frame(joined[,c("variables", "label", "contradiction", "rule")])

  # get the total number of data
  no_data <- data$num_rows
  
  # instantiate columns for return dataframe
  varname <- character(0)
  rule_applied <- character(0)
  no_contradict <- character(0)
  percentage <- double()
  
  for (row in 1:nrow(joined)){
    variables <- joined[row, "variables"]
    
    # evaluation <- str_extract_all(joined[row, "contradiction"], "<>|<=|>=|<|>")[[1]]
    variables_comb <- str_split(variables, " \\| ")[[1]]
    
    if (length(variables_comb) < 2){
      stop("need at least 2 variables for comparison")
    }
    
    expression <- joined[row, "contradiction"]
    
    # format variable name in contradiction expression
    # for(var in variables_comb){
    #   expression <- str_replace_all(expression, var, str_interp("data$${var}"))
    # }
    # print(expression)
    
    # special handling for dates in expression
    dates <- str_extract_all(joined[row, "contradiction"], "\\d{2}/\\d{2}/\\d{4}")[[1]]
    for (date_val in dates){
      expression <- str_replace_all(expression, date_val, str_interp("dmy(\"${date_val}\")"))
    }
    # print(expression)
    
    
    # --- Get contradicted data
    contradicted_data <- data
    expression <- str_split(expression, "&&")[[1]]
    for (exp in expression){
      
      exp <- str_interp("contradicted_data <- contradicted_data %>% dplyr::filter(${exp})")
      # contradicted_data <- contradicted_data %>% dplyr::filter(eval(parse_expr(exp)))
      
      eval(parse_expr(exp))
    }
    
    varname <- append(varname, variables)
    rule_applied <- append(rule_applied, joined["rule"])
    no_contradict <- append(no_contradict, str_interp("${nrow(contradicted_data)}/${no_data}"))
    percentage <- append(percentage, (nrow(contradicted_data)/no_data))
  }
  
  result <- data.frame(varname, rule_applied, no_contradict, percentage)
  return(list("contradicted_data" = contradicted_data, "result" = result))
}