#' Assess Integrity - duplication
#'
#' Check whether there are duplicate rows in pre-defined columns/variables
#'
#' @param data - arrow data table
#' @param check_all - whether to check duplicates over all variables
#' @param remove_dups - whether to remove duplicates
#' @param cross_item_metadata - cross item level metadata, expected data table object generated by prep_metadata function
#'
#' @return list of 2 items
#' - result: result summary data.frame
#' - duplicates: logical vector indicating whether each row is a duplicate
#' 
#' @import data.table arrow tidyverse
#' @export
#'
#' @examples
int_duplicates <- function(data, check_all=TRUE, remove_dups=FALSE, cross_item_metadata=NULL, plot_result = FALSE){
  varnames <- character(0)
  no_unique <- character(0)
  percentage_duplicates <- double()
  duplicates <- list()
  
  no_data <- data$num_rows
  # test duplicates, either based on all or selected columns (if defined in metadata)
  if(check_all){
    all_vars <- data$ColumnNames()
    is_duplicates <- data %>% 
      util_compute_duplicates(all_vars)
    
    n_dups <- length(which(is_duplicates))
    
    varnames <- append(varnames, "All variables")
    no_unique <- append(no_unique, str_interp("${no_data - n_dups}/${no_data}"))
    percentage_duplicates <- append(percentage_duplicates, (n_dups/no_data))
    
    duplicates[["all_vars"]] <- is_duplicates
    gc()
  }
  
  
  # check based on what is provided on metadata
  if (!is.null(cross_item_metadata)){
    multivariate_vars <- cross_item_metadata$multivariate_vars[check_unique==TRUE,]
    multivariate_vars <- as.data.frame(multivariate_vars[,c("variables", "label")])
    
    if(nrow(multivariate_vars) > 0){
      for (row in 1:nrow(multivariate_vars)){
      variables_comb <- str_split(multivariate_vars[row, "variables"], " \\| ")[[1]]

      is_duplicates <-  data %>% 
        util_compute_duplicates(variables_comb)
      
      # get number of duplicates
      n_dups <- length(which(is_duplicates))
      
      varnames <- append(varnames, multivariate_vars[row, "variables"])
      no_unique <- append(no_unique, str_interp("${no_data - n_dups}/${no_data}"))
      percentage_duplicates <- append(percentage_duplicates, (n_dups*100/no_data))
      
      # get multivariate label name
      label_name <- multivariate_vars[row, "label"]
      duplicates[[label_name]] <- is_duplicates
      }
    
    }

    gc()
  }
  
  result <- data.frame(varnames, no_unique, percentage_duplicates)
  
  if(plot_result){
    print(util_graphing_percentage(result, varnames, percentage_duplicates, title = "Percentage of duplicates"))
  }
  
  return(list(
    "result" = result,
    "duplicates" = duplicates
  ))
}