#' Utility function - Graphing utility
#'
#' graph result table using ggplot and plotly
#' 
#' @param data - the result dataframe generated by DQA functions
#' @param label - the column used for labeling (usually varname column)
#' @param percentage - column containing percentage to graph
#' @param fill - fill color for the graph
#' @param title - title for the plot
#'
#' @return histogram of the result
#' @export
#' @import tidyverse
#' @importFrom plotly ggplotly
#'
#' @examples

util_graphing_percentage <- function(data, label, title=NULL, percentage = percentage, fill= "#87ceeb") {
  graph <- data %>% 
    ggplot(
      aes(
        x = {{label}},
        y = {{percentage}}
      )
    ) + 
    geom_histogram(stat="identity", fill = "#87ceeb") + 
    coord_flip() +
    theme_bw()
  
  if(!is.null(title)){
    graph <- graph + ggtitle(title)
  }
  
  # plotly-fy the graph
  
  return(ggplotly(graph))
}
  