# Util to graph output as ggplot or plotly
#' Title
#'
#' @param data - the result dataframe generated by DQA functions
#' @param label - the column used for labeling (usually varname column)
#' @param percentage - column containing percentage to graph
#' @param fill - fill color for the graph
#'
#' @return
#' @export
#' @import tidyverse
#' @importFrom plotly ggplotly
#'
#' @examples

util_graphing_percentage <- function(data, label, percentage = percentage, fill= "#87ceeb") {
  graph <- data %>% 
    ggplot(
      aes(
        x = {{label}},
        y = {{percentage}}
      )
    ) + 
    geom_histogram(stat="identity", fill = "#87ceeb") + 
    coord_flip() +
    theme_bw()
  
  # plotly-fy the graph
  ggplotly(graph)
}
  